# OpenAPI Specification for Todo Application API

```yaml
openapi: 3.0.3
info:
  title: Todo Application API
  description: API for managing tasks in the full-stack todo application
  version: 1.0.0
  contact:
    name: API Support
    email: support@todoapp.com
servers:
  - url: https://api.todoapp.com/v1
    description: Production server
  - url: https://staging-api.todoapp.com/v1
    description: Staging server
  - url: http://localhost:8000/v1
    description: Development server

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid input
        '409':
          description: User already exists

  /auth/login:
    post:
      summary: Login user and get JWT tokens
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  token_type:
                    type: string
        '401':
          description: Invalid credentials

  /auth/refresh:
    post:
      summary: Refresh access token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
              required:
                - refresh_token
      responses:
        '200':
          description: New access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
        '401':
          description: Invalid refresh token

  /tasks:
    get:
      summary: Get all tasks for the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: status
          in: query
          description: Filter by task status
          schema:
            type: string
            enum: [active, completed]
        - name: priority
          in: query
          description: Filter by priority
          schema:
            type: string
            enum: [high, medium, low]
        - name: search
          in: query
          description: Search in task title and description
          schema:
            type: string
        - name: sort
          in: query
          description: Sort by field
          schema:
            type: string
            enum: [due_date, priority, title, created_at]
        - name: order
          in: query
          description: Sort order
          schema:
            type: string
            enum: [asc, desc]
            default: asc
        - name: limit
          in: query
          description: Number of tasks to return
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: offset
          in: query
          description: Number of tasks to skip
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/TaskResponse'
                  total:
                    type: integer
        '401':
          description: Unauthorized
    post:
      summary: Create a new task
      tags:
        - Tasks
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /tasks/{task_id}:
    get:
      summary: Get a specific task
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          description: Unauthorized
        '404':
          description: Task not found
    put:
      summary: Update a task
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Task not found
        '409':
          description: Concurrent modification detected (optimistic lock failure)
    delete:
      summary: Delete a task
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Task not found
        '409':
          description: Concurrent modification detected (optimistic lock failure)

  /tasks/{task_id}/complete:
    post:
      summary: Mark a task as complete
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task marked as complete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          description: Unauthorized
        '404':
          description: Task not found
        '409':
          description: Concurrent modification detected (optimistic lock failure)

  /tasks/{task_id}/reopen:
    post:
      summary: Reopen a completed task
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task reopened
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          description: Unauthorized
        '404':
          description: Task not found
        '409':
          description: Concurrent modification detected (optimistic lock failure)

  /tags:
    get:
      summary: Get all tags for the authenticated user
      tags:
        - Tags
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TagResponse'
        '401':
          description: Unauthorized
    post:
      summary: Create a new tag
      tags:
        - Tags
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagCreate'
      responses:
        '201':
          description: Tag created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagResponse'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '409':
          description: Tag already exists for user

  /tags/{tag_id}:
    put:
      summary: Update a tag
      tags:
        - Tags
      security:
        - BearerAuth: []
      parameters:
        - name: tag_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagUpdate'
      responses:
        '200':
          description: Tag updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagResponse'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Tag not found
    delete:
      summary: Delete a tag
      tags:
        - Tags
      security:
        - BearerAuth: []
      parameters:
        - name: tag_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Tag deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Tag not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserRegistration:
      type: object
      properties:
        username:
          type: string
          example: "johndoe"
        email:
          type: string
          format: email
          example: "john@example.com"
        password:
          type: string
          format: password
          example: "securePassword123"
      required:
        - username
        - email
        - password

    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
          format: email
        created_at:
          type: string
          format: date-time
        theme_preference:
          type: string
          enum: [light, dark, auto]
          default: auto

    TaskCreate:
      type: object
      properties:
        title:
          type: string
          example: "Buy groceries"
        description:
          type: string
          example: "Milk, eggs, bread"
        priority:
          type: string
          enum: [high, medium, low]
          default: medium
        due_date:
          type: string
          format: date-time
          example: "2023-12-31T23:59:59Z"
        tags:
          type: array
          items:
            type: string
          example: ["work", "shopping"]
        recurrence_pattern:
          type: string
          enum: [daily, weekly, monthly]
          example: "weekly"
      required:
        - title

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          example: "Buy groceries"
        description:
          type: string
          example: "Milk, eggs, bread"
        priority:
          type: string
          enum: [high, medium, low]
          default: medium
        due_date:
          type: string
          format: date-time
          example: "2023-12-31T23:59:59Z"
        status:
          type: string
          enum: [active, completed]
        tags:
          type: array
          items:
            type: string
          example: ["work", "shopping"]
        version:
          type: integer
          description: Used for optimistic locking

    TaskResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [active, completed]
        priority:
          type: string
          enum: [high, medium, low]
        due_date:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        tags:
          type: array
          items:
            $ref: '#/components/schemas/TagResponse'
        recurrence_pattern:
          type: string
          enum: [daily, weekly, monthly]
        version:
          type: integer
          description: Used for optimistic locking

    TagCreate:
      type: object
      properties:
        name:
          type: string
          example: "work"
        color:
          type: string
          format: hex-color
          example: "#FF5733"
      required:
        - name

    TagUpdate:
      type: object
      properties:
        name:
          type: string
          example: "work"
        color:
          type: string
          format: hex-color
          example: "#FF5733"

    TagResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        color:
          type: string
          format: hex-color
        created_at:
          type: string
          format: date-time

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    NotFoundError:
      description: The specified resource was not found
    ValidationError:
      description: Request validation failed
    ConcurrentModificationError:
      description: The resource was modified by another user since retrieval (optimistic lock failure)
```